/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mibs.cabinet.downstream;

import org.junit.Test;

import mibs.init.cabinet.CabinetDownstream;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        CabinetDownstream classUnderTest = new CabinetDownstream();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
